export enum NodeEnvironments {
  Production = "production",
  Developmemt = "development",
  Test = "test",
}

export enum ConfigKeys {
  CONFIG_ADAPTOR = "CONFIG_ADAPTOR",
  CACHE_ADAPTOR = "CACHE_ADAPTOR",
  ENCRYPTION_KEY = "ENCRYPTION_KEY",
  AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY",
  CONFIG_ADAPTOR_CONNECTION_STRING = "CONFIG_ADAPTOR_CONNECTION_STRING",
  CONFIG_CACHE_CONNECTION_STRING = "CONFIG_CACHE_CONNECTION_STRING",
  TOKEN_VALIDITY_DURATION_IN_DAYS = "TOKEN_VALIDITY_DURATION_IN_DAYS",
}
