export enum ConfigKeys {
  CONFIG_ADAPTOR = "CONFIG_ADAPTOR",
  CACHE_ADAPTOR = "CACHE_ADAPTOR",
  CREDENTIALS_ENCRYPTION_KEY = "CREDENTIALS_ENCRYPTION_KEY",
  AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY",
  CONFIG_ADAPTOR_CONNECTION_STRING = "CONFIG_ADAPTOR_CONNECTION_STRING",
  CACHE_ADAPTOR_CONNECTION_STRING = "CACHE_ADAPTOR_CONNECTION_STRING",
}
